### ISSUE TITLE
Feature request: add ID auto counter

### ISSUE THREAD

**Issue by salemalem** [Kirlovon/AloeDB#14]
It would be cool if aloe db will have built-in ID counter, so I don't have to worry about its uniqueness)
String uniqueness or number counter options should be provided.

**Comment by Kirlovon** [comment]
Hi! Maybe in future releases i will add mandatory unique id for documents. For now, you can use [nanoid](https://github.com/ai/nanoid) or simmilar modules.

**Comment by salemalem** [comment]
_For now, you can use nanoid or simmilar modules._
Goal is to stay zero dependency for database)

**Comment by Kirlovon** [comment]
"Zero dependency" refers only to the internal structure of AloeDB. Your project can have as many dependencies as you want, it all depends on your needs. 

You can write the id generation function yourself, or even copy the code from the nanoid repository. Will it count as a dependency in that case? 😀
